//! The DecisionSchema IR: the DMMF-analog artifact. One canonical,
//! serializable description of a question set; both authoring surfaces
//! (hand-written JSON and the derive macros) lower to exactly this.

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{JevError, JevResult};
use crate::question::Decision;
use crate::wire::{Instructions, NoulCriteria, WireQuestion};

/// Current IR version (`"jev"` field in the artifact).
pub const SCHEMA_VERSION: u32 = 1;

/// Whether a question's criteria are compile-time literals or supplied
/// per call through the criteria editor.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CriteriaSource {
    /// Criteria live in the artifact.
    #[default]
    Static,
    /// Criteria are runtime-supplied; the artifact records the marker only.
    Runtime,
}

impl CriteriaSource {
    /// Serde skip helper: only serialize the non-default source.
    #[must_use]
    pub const fn is_static(&self) -> bool {
        matches!(self, Self::Static)
    }
}

/// Documentation of the state payload: descriptions only, no validation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StateSpec {
    /// What this state represents.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub describe: Option<String>,
    /// Field name to description (only described fields are listed).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub fields: BTreeMap<String, String>,
}

/// A question's shape in the IR. Mirrors the wire question plus the
/// `criteria_source` marker for runtime-parameterized questions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum QuestionSpec {
    /// Choice: option set with rubric descriptions.
    Choice {
        /// What the model should decide.
        instructions: Instructions,
        /// Option key to description (`None` = no extra detail).
        #[serde(default)]
        criteria: BTreeMap<String, Option<Instructions>>,
        /// Static literals or runtime editor values.
        #[serde(default, skip_serializing_if = "CriteriaSource::is_static")]
        criteria_source: CriteriaSource,
    },
    /// Score: ordered rubric.
    Score {
        /// What the model should rate.
        instructions: Instructions,
        /// Ordered level descriptions.
        #[serde(default)]
        criteria: Vec<Instructions>,
        /// Static literals or runtime editor values.
        #[serde(default, skip_serializing_if = "CriteriaSource::is_static")]
        criteria_source: CriteriaSource,
    },
    /// Noul: P(yes) with optional pole criteria.
    Noul {
        /// The yes/no question.
        instructions: Instructions,
        /// Optional pole descriptions.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        criteria: Option<NoulCriteria>,
    },
}

impl QuestionSpec {
    /// The primitive's wire name.
    #[must_use]
    pub fn kind_str(&self) -> &'static str {
        match self {
            Self::Choice { .. } => "choice",
            Self::Score { .. } => "score",
            Self::Noul { .. } => "noul",
        }
    }

    /// Lowers the spec to a wire question. Runtime-source specs with empty
    /// criteria fail loudly: they must go through the criteria editor.
    pub fn into_wire(&self, id: &str) -> JevResult<WireQuestion> {
        match self {
            Self::Choice {
                instructions,
                criteria,
                criteria_source,
            } => {
                if matches!(criteria_source, CriteriaSource::Runtime) && criteria.is_empty() {
                    return Err(JevError::MissingCriteria { id: id.to_owned() });
                }
                Ok(WireQuestion::Choice {
                    instructions: instructions.clone(),
                    criteria: criteria.clone(),
                })
            }
            Self::Score {
                instructions,
                criteria,
                criteria_source,
            } => {
                if matches!(criteria_source, CriteriaSource::Runtime) && criteria.is_empty() {
                    return Err(JevError::MissingCriteria { id: id.to_owned() });
                }
                Ok(WireQuestion::Score {
                    instructions: instructions.clone(),
                    criteria: criteria.clone(),
                })
            }
            Self::Noul {
                instructions,
                criteria,
            } => Ok(WireQuestion::Noul {
                instructions: instructions.clone(),
                criteria: criteria.clone(),
            }),
        }
    }
}

/// The schema artifact: versioned, serializable, diffable. Generated by
/// the `JevQuestions` derive or hand-authored as JSON.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecisionSchema {
    /// IR version; must equal [`SCHEMA_VERSION`].
    pub jev: u32,
    /// The model release thresholds were calibrated against, if pinned.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub calibrated_for: Option<String>,
    /// Optional state documentation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<StateSpec>,
    /// The question set, keyed by question id.
    pub questions: BTreeMap<String, QuestionSpec>,
}

/// Jev cardinality limits, from the API reference.
#[derive(Debug, Clone, Copy)]
pub struct Limits {
    /// Maximum choice options per question.
    pub max_choice_options: usize,
    /// Minimum score levels.
    pub min_score_levels: usize,
    /// Maximum score levels.
    pub max_score_levels: usize,
}

impl Default for Limits {
    fn default() -> Self {
        Self {
            max_choice_options: 255,
            min_score_levels: 2,
            max_score_levels: 10,
        }
    }
}

impl DecisionSchema {
    /// Starts an empty schema at the current IR version.
    #[must_use]
    pub fn new(calibrated_for: Option<String>) -> Self {
        Self {
            jev: SCHEMA_VERSION,
            calibrated_for,
            state: None,
            questions: BTreeMap::new(),
        }
    }

    /// Chainable: attach state documentation.
    #[must_use]
    pub fn with_state(mut self, state: StateSpec) -> Self {
        self.state = Some(state);
        self
    }

    /// Chainable: add one question spec.
    #[must_use]
    pub fn with_question(mut self, id: &str, spec: QuestionSpec) -> Self {
        self.questions.insert(id.to_owned(), spec);
        self
    }

    /// Validates all schema invariants. Every consumer (`load`, `query`,
    /// `to_json_pretty`) runs this first; hand-edited artifacts fail here.
    pub fn validate(&self) -> JevResult<()> {
        if self.jev != SCHEMA_VERSION {
            return Err(JevError::Schema(format!(
                "unsupported IR version {} (expected {SCHEMA_VERSION})",
                self.jev
            )));
        }
        if self.questions.is_empty() {
            return Err(JevError::Schema(
                "a schema must declare at least one question".to_owned(),
            ));
        }
        let limits = Limits::default();
        for (id, spec) in &self.questions {
            if id.trim().is_empty() {
                return Err(JevError::Schema(
                    "question ids must be non-empty".to_owned(),
                ));
            }
            match spec {
                QuestionSpec::Choice {
                    instructions,
                    criteria,
                    criteria_source,
                } => {
                    if !instructions.is_non_empty() {
                        return Err(JevError::Schema(format!(
                            "question `{id}` has empty instructions"
                        )));
                    }
                    let runtime = matches!(criteria_source, CriteriaSource::Runtime);
                    if criteria.is_empty() && !runtime {
                        return Err(JevError::Schema(format!(
                            "choice `{id}` needs at least one option"
                        )));
                    }
                    if !criteria.is_empty() && runtime {
                        return Err(JevError::Schema(format!(
                            "choice `{id}` is marked runtime but carries static criteria"
                        )));
                    }
                    if criteria.len() > limits.max_choice_options {
                        return Err(JevError::Schema(format!(
                            "choice `{id}` has {} options; max is {}",
                            criteria.len(),
                            limits.max_choice_options
                        )));
                    }
                }
                QuestionSpec::Score {
                    instructions,
                    criteria,
                    criteria_source,
                } => {
                    if !instructions.is_non_empty() {
                        return Err(JevError::Schema(format!(
                            "question `{id}` has empty instructions"
                        )));
                    }
                    let runtime = matches!(criteria_source, CriteriaSource::Runtime);
                    if !runtime
                        && !(limits.min_score_levels..=limits.max_score_levels)
                            .contains(&criteria.len())
                    {
                        return Err(JevError::Schema(format!(
                            "score `{id}` needs {}..={} levels, has {}",
                            limits.min_score_levels,
                            limits.max_score_levels,
                            criteria.len()
                        )));
                    }
                    if criteria.is_empty() && !runtime {
                        return Err(JevError::Schema(format!(
                            "score `{id}` needs at least {} levels",
                            limits.min_score_levels
                        )));
                    }
                    if !criteria.is_empty() && runtime {
                        return Err(JevError::Schema(format!(
                            "score `{id}` is marked runtime but carries static criteria"
                        )));
                    }
                }
                QuestionSpec::Noul { instructions, .. } => {
                    if !instructions.is_non_empty() {
                        return Err(JevError::Schema(format!(
                            "question `{id}` has empty instructions"
                        )));
                    }
                }
            }
        }
        Ok(())
    }

    /// Loads and validates an artifact from disk.
    pub fn load(path: impl AsRef<Path>) -> JevResult<Self> {
        let text = std::fs::read_to_string(path)?;
        let schema: Self = serde_json::from_str(&text)?;
        schema.validate()?;
        Ok(schema)
    }

    /// Serializes (pretty) to a string, validating first.
    pub fn to_json_pretty(&self) -> JevResult<String> {
        self.validate()?;
        Ok(serde_json::to_string_pretty(self)?)
    }

    /// Writes the pretty artifact to disk.
    pub fn save(&self, path: impl AsRef<Path>) -> JevResult<()> {
        std::fs::write(path, self.to_json_pretty()?)?;
        Ok(())
    }

    /// Starts composing a dynamic query against this schema.
    #[must_use]
    pub fn query(&self) -> SchemaQueryBuilder<'_> {
        SchemaQueryBuilder {
            schema: self,
            state: None,
            ids: Vec::new(),
        }
    }
}

/// Dynamic (untyped) query composition: ask a subset of the schema's
/// questions against some state, producing a wire-ready [`Decision`].
///
/// Note: questions marked `criteria_source: "runtime"` cannot be executed
/// from this builder in 0.1.0 — runtime criteria are a derive-surface
/// feature (criteria editors); use [`DynChoice`](crate::DynChoice) for
/// fully dynamic composition.
pub struct SchemaQueryBuilder<'a> {
    schema: &'a DecisionSchema,
    state: Option<serde_json::Value>,
    ids: Vec<String>,
}

impl SchemaQueryBuilder<'_> {
    /// Sets the state payload (any serializable value).
    pub fn state(mut self, state: impl Serialize) -> JevResult<Self> {
        self.state = Some(serde_json::to_value(state)?);
        Ok(self)
    }

    /// Adds a question by id; unknown ids fail immediately.
    pub fn ask(mut self, id: &str) -> JevResult<Self> {
        if !self.schema.questions.contains_key(id) {
            return Err(JevError::UnknownQuestion { id: id.to_owned() });
        }
        self.ids.push(id.to_owned());
        Ok(self)
    }

    /// Asks every question in the schema.
    #[must_use]
    pub fn ask_all(mut self) -> Self {
        self.ids = self.schema.questions.keys().cloned().collect();
        self
    }

    /// Builds the decision.
    pub fn build(self) -> JevResult<Decision> {
        self.schema.validate()?;
        if self.ids.is_empty() {
            return Err(JevError::Schema(
                "query asks no questions; call ask()/ask_all()".to_owned(),
            ));
        }
        let state = self.state.ok_or(JevError::MissingState)?;
        let mut questions = BTreeMap::new();
        for id in &self.ids {
            let spec = &self.schema.questions[id];
            questions.insert(id.clone(), spec.into_wire(id)?);
        }
        Ok(Decision::from_parts(state, questions))
    }
}
